version: "3.7"

services:
  database:
    image: postgres
    container_name: queriesChallenge
    restart: always
    ports:
     - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=database
    volumes:
       - pgdata:/data/postgres
  app:
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local